### ISSUE TITLE
about pre-training model

### ISSUE THREAD

**Issue by futureisatyourhand** [baaivision/EVA#1]
hello,could you please post the pre-training model, e.g., vit-base/16 or vit-large/16?

Thanks

**Comment by Yuxin-CV** [comment]
Hi, for the based-sized and large-sized ViTs, please refer to other excellent open-sourced projects such as:
- https://github.com/microsoft/unilm/tree/master/beit2
- https://github.com/zejiangh/MILAN

We adopt similar approaches as them.

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.

**Comment by Yuxin-CV** [comment]
Hi, we have release our large-sized model: https://github.com/baaivision/EVA/tree/master/eva#eva-l-learning-better-mim-representations-from-eva-clip

Also at timm: https://github.com/rwightman/pytorch-image-models#dec-8-2022
