### ISSUE TITLE
How to train with custom dataset?

### ISSUE THREAD

**Issue by Skyninth** [baaivision/EVA#13]
I have custom data with coco format, how can I train with my own data?

**Comment by Yuxin-CV** [comment]
Thanks for your interest in our work.

We bulid our detector based on Detectron2, please refer to https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html for training / fine-tuning on your custom datasets.

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
