### ISSUE TITLE
use_cls seems likes not used in linear prob

### ISSUE THREAD

**Issue by Dongshengjiang** [baaivision/EVA#14]
use_cls seems likes not used in linear prob

**Comment by Yuxin-CV** [comment]
Set `use_cls = True` disable GAP feature (_i.e._, disable `use_mean_pooling`) and use `cls_token` for linear probing.

https://github.com/baaivision/EVA/blob/9cdafd9035045042c5ceb54a4d1af4ed9a9942dd/eva/run_class_finetuning.py#L160-L162

**Comment by Yuxin-CV** [comment]
We just added instructions to re-produce the linear probing results: https://github.com/baaivision/EVA/tree/master/eva#linear-probing-1.

**Comment by Dongshengjiang** [comment]
Thanks

**Comment by Dongshengjiang** [comment]
Thanks

**Comment by Dongshengjiang** [comment]
Thanks
