### ISSUE TITLE
Where is EVA G?

### ISSUE THREAD

**Issue by OpenJarvisAI** [baaivision/EVA#152]
<img width="814" alt="image" src="https://github.com/baaivision/EVA/assets/136460643/7ed76865-de3d-4f8b-b3f6-9b7b79e795df">

Where does these EVA G indicates for?

**Comment by Quan-Sun** [comment]
It's [EVA-CLIP-g](https://github.com/baaivision/EVA/tree/master/EVA-CLIP#eva-01-clip-series) with 1B parameters.

**Comment by OpenJarvisAI** [comment]
What's the input resolution btw?

**Comment by Quan-Sun** [comment]
> What's the input resolution btw?

it's 224x224.
