### ISSUE TITLE
The MIM target for EVA

### ISSUE THREAD

**Issue by vateye** [baaivision/EVA#16]
Sorry to bother you. I notice that the EVA utilizes the projected CLIP feature as the target, I am wondering why not use the feature before projection since it is the original representation of ViT model. Is is determined by the performance of experiments?

**Comment by Yuxin-CV** [comment]
Yeah, in our experiment with base sized and large sized ViTs, the projected CLIP feature gives better results.

**Comment by vateye** [comment]
Thanks, it did shock me.
