### ISSUE TITLE
The requirement of GPU memory for inference for the instance segmentation

### ISSUE THREAD

**Issue by yk-pku** [baaivision/EVA#18]
Hi, I  find the problem of "out of memory" when conducting inference on COCO2017 val using 3090 (24G). I also see the batch_size is default set to 1 during inference. Therefore, I just wonder what the minimum required GPU memory.

**Comment by Yuxin-CV** [comment]
We use 40G A100 GPU in object detection & instance segmentation experiment. If you use 24G cards, please try smaller input resolution such as 768x768 or 1024x1024. Notice that the performance will also degenerate with smaller inputs.

**Comment by Yuxin-CV** [comment]
If you are interested in training with a smaller backbone, we also provide EVA-L (vanilla ViT-L w/ 303M parameters) with up to 89.2% top-1 acc on IN-1K: https://github.com/baaivision/EVA/tree/master/eva#eva-l-learning-better-mim-representations-from-eva-clip.  

To our knowledge, EVA-L is the best open-sourced large-sized vision encoder to date. Try it out if you are interested.

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.

**Comment by otakutyrant** [comment]
> We use 40G A100 GPUs in object detection & instance segmentation experiment. If you use 24G cards, please try smaller input resolution such as 768x768 or 1024x1024. Notice that the performance will also degenerate with smaller inputs.

I am trying to evaluate the EVA model `https://huggingface.co/BAAI/EVA/blob/main/eva_coco_seg.pth` in COCO instance segementation. I have only GTX 1080 and it always is out of memory even after I have set `image_size` to `192` in `/path/to/EVA/det/projects/ViTDet/configs/common/coco_loader_lsj_1536.py`. If I does not mistake the config, it can't be helped.
