### ISSUE TITLE
The pos_emb used in eva pretraining and eva det.

### ISSUE THREAD

**Issue by whut2962575697** [baaivision/EVA#20]
Hello，thanks for yor great work! Sorry to bother you, but I have some doubts about the pos emb in the codes.
(1) I find the pos_emb used in eva pretraining is abs_pos_emb   
in 68 Line which set    parser.set_defaults(abs_pos_emb=True)
(https://github.com/baaivision/EVA/blob/master/eva/run_eva_pretraining.py)
As i know, in the original beit codes, they use the rel_pos. Why  do you need to make this modification, is this setting helpful for pre-training or some downstream tasks?  
(2) I found that when performing detection tasks（eva_det）, vit's pos emb uses rel pos, which is inconsistent with the pre-training stage

**Comment by Yuxin-CV** [comment]
Using `rel pos` slows down the pre-training process and makes ViTs fragile to scale up.

Originally, `rel pos` is not a part of vanilla ViTs.

Using `rel pos` in some downstream tasks such as object detection can boost the performance. Please refer to [ViTDet](https://arxiv.org/abs/2203.16527) for a detailed study.

**Comment by whut2962575697** [comment]
Thanks！I got it.

**Comment by Yuxin-CV** [comment]
> Thanks！I got it.

Also see a recent paper on this: https://arxiv.org/pdf/2212.06138.pdf

<img width="600" alt="image" src="https://user-images.githubusercontent.com/57927171/207224854-4d559055-5488-4270-a026-8ea333ebd4de.png">
