### ISSUE TITLE
The  intermediate fine-tuning scripts in object 365

### ISSUE THREAD

**Issue by whut2962575697** [baaivision/EVA#21]
Can you share the  intermediate fine-tuning scripts and logs in object 365?

**Comment by jetyingjia** [comment]
> 

In some paper, the training dataset is train+val(8w-5k),  Can you share your config in this paper?

**Comment by Yuxin-CV** [comment]
> > 
> 
> In some paper, the training dataset is train+val(8w-5k), Can you share your config in this paper?

We use O365 V1.0

**Comment by whut2962575697** [comment]
Hello, thanks for your reply. But as i know obj365 v1.0 only has 66w imgs，obj365 v2.0 has 174w imgs. Do you use only  66w imgs for training?

**Comment by Yuxin-CV** [comment]
Please refer to issue #22 


I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
