### ISSUE TITLE
Problem about object365 dataset

### ISSUE THREAD

**Issue by Dave19950** [baaivision/EVA#22]
Is the released obj365 detection model trained on offcial Object365 dataset(174W), and validate on the val dataset(8W)

**Comment by Yuxin-CV** [comment]
Yes, we use O365 V1.0

**Comment by Yuxin-CV** [comment]
The val set images are also used

**Comment by Yuxin-CV** [comment]
We don't have a evaluation result on o365

**Comment by Dave19950** [comment]
OK, understand, So the total valset of OBJ365 is added in training?

**Comment by Yuxin-CV** [comment]
exactly

**Comment by Dave19950** [comment]
OK, Thanks!

**Comment by whut2962575697** [comment]
> 

As  i know obj365 v1.0 only has 66w imgs，obj365 v2.0 has 174w imgs. Do you use only 66w imgs for training?

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
