### ISSUE TITLE
ImageNet 1K results without 21k Intermediate Fine-tune 

### ISSUE THREAD

**Issue by whut2962575697** [baaivision/EVA#24]
I see you achieve good result 89.2 in imagenet 1k with eva_l_psz14_21k_ft，but what can it achieve when without  21k intermediate fine-tune?

**Comment by Yuxin-CV** [comment]
Please refer to https://github.com/baaivision/EVA/tree/master/eva#performance-of-eva-l-on-imagenet-1k

**Comment by Yuxin-CV** [comment]
Also at timm: https://github.com/rwightman/pytorch-image-models#dec-8-2022

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
