### ISSUE TITLE
Custom downsteam object detection task (only bbox no mask )

### ISSUE THREAD

**Issue by CarlHuangNuc** [baaivision/EVA#27]
Hi Author,

      I want to  training a custom object detection task base on your excellent work.
But i found our dataset do not have mask label. 
      How to remove all mask requirement in your coco detection task ?

**Comment by Yuxin-CV** [comment]
Hi @CarlHuangNuc, this is essentially an issue about object detector design using [Detectron2](https://github.com/facebookresearch/detectron2), which is not directly related to our work. 

Personally, I suggest you only load the weight of the detector (w/ loading mask head). I also believe there are other elegant solutions which are available in the [Detectron2](https://github.com/facebookresearch/detectron2) community.

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.

**Comment by xinlin-xiao** [comment]
> 嗨，作者，
> 
> ```
>   I want to  training a custom object detection task base on your excellent work.
> ```
> 
> 但是我发现我们的数据集没有掩码标签。如何删除可可检测任务中的所有掩码要求？



> Hi Author,
> 
> ```
>   I want to  training a custom object detection task base on your excellent work.
> ```
> 
> But i found our dataset do not have mask label. How to remove all mask requirement in your coco detection task ?

hi,did find a way to  fix it ?

**Comment by wangkaihong** [comment]
You may add this line to your config file:

`[model.roi_heads.pop(k) for k in ["mask_in_features", "mask_pooler", "mask_head"]]
`
