### ISSUE TITLE
Inference with Eva

### ISSUE THREAD

**Issue by mohamedettebayo** [baaivision/EVA#29]
Can anyone please show me how to perform inference (which script or command to use) on single or multiple image after training the Eva module on my custom datasets?

**Comment by AndrewTKent** [comment]
I'm also interested in this -

**Comment by luckcodingdog** [comment]
Me, too

**Comment by 1049451037** [comment]
me too...

**Comment by Yuxin-CV** [comment]
please refer to https://github.com/baaivision/EVA/issues/56 if you are still interested in loading EVA-02 as a feat extractor.
