### ISSUE TITLE
Will you publish a config for instance segmentation ?

### ISSUE THREAD

**Issue by aquexel** [baaivision/EVA#3]
Hi Guys !
Thank you for your job !
Will you publish a folder with instance segmentation and when ?
Thank you !

**Comment by Yuxin-CV** [comment]
In one day, thanks for your attention

**Comment by Yuxin-CV** [comment]
The code & models have been released (`Nov 22, 2022`).

I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
