### ISSUE TITLE
warning while training

### ISSUE THREAD

**Issue by mohamedettebayo** [baaivision/EVA#31]
**hi there 
i am experiencing this warning while training** 

01/13 09:56:11 d2.engine.train_loop]: Starting training from iteration 0
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
[01/13 09:56:45 d2.utils.events]:  eta: 20:18:34  iter: 19  total_loss: 14.61  loss_cls_stage0: 4.223  loss_box_reg_stage0: 0.002018  loss_cls_stage1: 4.189  loss_box_reg_stage1: 0.003367  loss_cls_stage2: 4.404  loss_box_reg_stage2: 0.00404  loss_mask: 0.693  loss_rpn_cls: 0.6935  loss_rpn_loc: 0.3204  time: 1.6258  data_time: 0.0255  lr: 9.7405e-07  max_mem: 28114M
/usr/local/lib/python3.8/dist-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

**Comment by Thatboy7** [comment]
hello,friend! i meet the same question. except this, 'cuda out of memory' always happend. could u please show me your detect config ? and i wanna know your memory size（mine is 32g ）

**Comment by mohamedettebayo** [comment]
you need to change batch size to 1 if you are training on 32GB of GPU

**Comment by amanikiruga** [comment]
@Quan-Sun is this warning normal? I also get it when trying to train EVA-02 base MIM_to_COCO model on google colab.
