### ISSUE TITLE
Train instance segmentation using EVA pretrained on custom dataset

### ISSUE THREAD

**Issue by mohdsaqibdd2b** [baaivision/EVA#33]
I am seeking the instructions on how to train an instance segmentation model using an EVA pretrained model on my custom data. I would be grateful if someone could provide me with the necessary steps and best practices to accomplish this task. Thanks.

**Comment by havardox** [comment]
Ditto

**Comment by Furkanicten1239** [comment]
In lazyconfig_train_net.py, they say "It can be used to train any models or dataset as long as they can be
instantiated by the recursive construction defined in the given config file.". However, example config files they have doesn't include number of classes or sth like that. I couldn't find anything to configure their model for custom dataset :/

**Comment by Yuxin-CV** [comment]
Our codebase is built on detectron2, please refer to https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html if you want  to train on custom datasets.
