### ISSUE TITLE
EVA train on object365

### ISSUE THREAD

**Issue by Shiro-LK** [baaivision/EVA#34]
Hello, 

I am trying to work with EVA pretrained on object365 but  I have few questions about it. I try to load the model and get these message : 
```

Some model parameters or buffers are not found in the checkpoint:
roi_heads.mask_head.deconv.{bias, weight}
roi_heads.mask_head.mask_fcn1.norm.{bias, weight}
roi_heads.mask_head.mask_fcn1.weight
roi_heads.mask_head.mask_fcn2.norm.{bias, weight}
roi_heads.mask_head.mask_fcn2.weight
roi_heads.mask_head.mask_fcn3.norm.{bias, weight}
roi_heads.mask_head.mask_fcn3.weight
roi_heads.mask_head.mask_fcn4.norm.{bias, weight}
roi_heads.mask_head.mask_fcn4.weight
roi_heads.mask_head.predictor.{bias, weight}
```

Does that mean the model has not been trained with a mask rcnn architecture ? So, only object detection pretraining ? 

Would it be possible to share the lazy config file of this checkpoint ? 

Thank !

**Comment by Yuxin-CV** [comment]
Please notice that we use Cascade R-CNN as the detector.
