### ISSUE TITLE
Whether the NUM_FRAMES should be set to 16 instead of 8 on K700 fine-tune phrase?

### ISSUE THREAD

**Issue by peiliu0408** [baaivision/EVA#36]
https://github.com/baaivision/EVA/blob/4f3f50a044c7765b8ecbfde0629f3a9f6b78ea30/video/configs/kinetics700_ft.yaml#L6
as mentioned as titile, the num_frames should be set to 16 in fine-tune phrase after k722 pretraining, but default value is 8.

**Comment by Yuxin-CV** [comment]
Thank for pointing this out. The NUM_FRAMES should be set to 16 for the final ft phase.

**Comment by Yuxin-CV** [comment]
Please also refer to our training log: https://github.com/baaivision/EVA/blob/597b8a732f080a23c06b3c2fbc5b21f77a51693c/logs/video/ft_k700_log.txt
