### ISSUE TITLE
how many types in the pre-trained model? as coco?

### ISSUE THREAD

**Issue by MollyHoo** [baaivision/EVA#37]
how many types in the pre-trained model? as coco?

**Comment by Yuxin-CV** [comment]
Hi, if you are interested in the detection part, please read the [README](https://github.com/baaivision/EVA/blob/master/det/README.md) first.

**Comment by Yuxin-CV** [comment]
The issue is no longer active, as such I'm closing this. Feel free to ask if you have further questions.
