### ISSUE TITLE
.py file for single image inference

### ISSUE THREAD

**Issue by nikolaydyankov** [baaivision/EVA#4]
Thank you so much for releasing this, I can't wait to try it on my own data. Are you planning to release a py script for single image inference?

**Comment by Yuxin-CV** [comment]
Hi, please refer to https://github.com/baaivision/EVA/blob/master/clip/README.md for single image inference with EVA-CLIP

**Comment by nikolaydyankov** [comment]
It looks like adapting that code to do segmentation is beyond me, I'll just wait for examples to pop up from somewhere.

**Comment by nikolaydyankov** [comment]
For example when I do `model = build_segmentor(cfg.model)` I'm getting this:

`KeyError: 'EncoderDecoderMask2Former is not in the models registry`

**Comment by Yuxin-CV** [comment]
This issue is no longer active in 20 days, as such I'm closing this. Feel free to ask if you have further questions.
