### ISSUE TITLE
RuntimeError: EncoderDecoderMask2FormerAug: BEiTAdapter: "compute_indices_weights_cubic" not implemented for 'Half'

### ISSUE THREAD

**Issue by QX-N** [baaivision/EVA#40]
Hi, I met a problem with this bug. The configs used are the same as yours. 
![image](https://user-images.githubusercontent.com/108463784/224278367-e4840d9f-a384-4776-9e4b-5916ef3a87bb.png)

**Comment by eternal-f1ame** [comment]
What was the solution to this?
