### ISSUE TITLE
EVA 2.0-CLIP

### ISSUE THREAD

**Issue by vateye** [baaivision/EVA#41]
Hi, nice work to EVA-2.0, is there any plan to try EVA 2.0 training on CLIP or scaling EVA 2.0 to giant size?

**Comment by vateye** [comment]
Is there any information for 4.7B model? I am excited about it.

**Comment by Yuxin-CV** [comment]
Hi @vateye, we have released all EVA-CLIP models and inference code at https://github.com/baaivision/EVA/tree/master/EVA-CLIP#model-card. 

We offer performant CLIP models at all scales, range from 150M to 4.7B. Try them out if you are interested.

**Comment by vateye** [comment]
Thanks for your response. Is there any technique report for it?

**Comment by Yuxin-CV** [comment]
> Thanks for your response. Is there any technical report for it?

The technical report are coming very soon.

**Comment by Yuxin-CV** [comment]
> Hi, can you explain why Rope and subln is not used for EVA-2-e (CLIP)?

Because the 4.7B EVA-CLIP-E were trained before we started to explore RoPE, SwiGLU and sub-LN, etc.

**Comment by vateye** [comment]
> > Thanks for your response. Is there any technical report for it?
> 
> The technical report are coming very soon.

Hi, is there any update for EVA-CLIP report?

**Comment by Yuxin-CV** [comment]
> > > Thanks for your response. Is there any technical report for it?
> > 
> > 
> > The technical report are coming very soon.
> 
> Hi, is there any update for EVA-CLIP report?

Coming in 24h.

**Comment by Yuxin-CV** [comment]
The report is available at https://arxiv.org/abs/2303.15389

**Comment by mactavish91** [comment]
> The report is available at https://arxiv.org/abs/2303.15389

Hello, could you tell me how is eva-e initialized?
