### ISSUE TITLE
About the EVA-02 on Arxiv

### ISSUE THREAD

**Issue by YTEP-ZHI** [baaivision/EVA#43]
I sincerely suggest change all the title(EVA-02) mentioned in this paper **back to black**. Too many words in red is extremely distracting and hurt the overall reading experience.

**Comment by Yuxin-CV** [comment]
Hi @YTEP-ZHI, thanks for the suggestion. 

Indeed, EVA-02 in red is a personal choice. If you prefer EVA-02 in black, I suggest download the source from arxiv and compile it with your favorite color.
