### ISSUE TITLE
Version of Xformers

### ISSUE THREAD

**Issue by coni-coco** [baaivision/EVA#46]
What is your version of Xformers?

Xformers >= 0.0.16 needs torch >=1.13

**Comment by Yuxin-CV** [comment]
Hi @coni-coco, we build xformer from source using commit https://github.com/facebookresearch/xformers/tree/7e05e2caaaf8060c1c6baadc2b04db02d5458a94

**Comment by ShuxunoO** [comment]
TypeError                                 Traceback (most recent call last)
Cell In[2], line 7
      4 text = tokenizer(["a diagram", "a dog", "a cat"]).to(device)
      6 with torch.no_grad(), torch.cuda.amp.autocast():
----> 7     image_features = model.encode_image(image)
      8     text_features = model.encode_text(text)
      9     image_features /= image_features.norm(dim=-1, keepdim=True)

File /data/sswang/NFT_search/EVA/EVA-CLIP/utils/../rei/eva_clip/model.py:302, in CustomCLIP.encode_image(self, image, normalize)
    301 def encode_image(self, image, normalize: bool = False):
--> 302     features = self.visual(image)
    303     return F.normalize(features, dim=-1) if normalize else features

File [~/anaconda3/envs/rei/lib/python3.8/site-packages/torch/nn/modules/module.py:1130](https://vscode-remote+ssh-002dremote-002b172-002e18-002e32-002e116.vscode-resource.vscode-cdn.net/data/sswang/NFT_search/EVA/EVA-CLIP/utils/~/anaconda3/envs/rei/lib/python3.8/site-packages/torch/nn/modules/module.py:1130), in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /data/sswang/NFT_search/EVA/EVA-CLIP/utils/../rei/eva_clip/eva_vit_model.py:529, in EVAVisionTransformer.forward(self, x, return_all_features)
    527 if return_all_features:
...
    212     )
    213 x = x.reshape(B, N, -1)
    214 x = self.inner_attn_ln(x)

**TypeError: memory_efficient_attention() got an unexpected keyword argument 'scale'**

在执行安装依赖
pip install -r requirements.txt
Xformers从0.0.18一直安装到0.0.13  执行官方给的demo时报错，不知道是不是Xformer的版本问题

**Comment by ShuxunoO** [comment]
> Hi @coni-coco, we build xformer from source using commit https://github.com/facebookresearch/xformers/tree/7e05e2caaaf8060c1c6baadc2b04db02d5458a94
> 
> But we believe using the latest version of pytorch & xformer also works.

I upgrade my dependencies as following：

torch                     2.0.1                  
torchvision               0.15.2           
xformers                  0.0.20        
nvidia-cudnn-cu11         8.5.0.96
……

It works！

**Comment by seabearlmx** [comment]
Hi @ShuxunoO, when you follow these versions:

torch 2.0.1
torchvision 0.15.2
xformers 0.0.20
nvidia-cudnn-cu11 8.5.0.96

the mmcv and mmsegmentation version is?
