### ISSUE TITLE
calculation in the detection code when xattn=False

### ISSUE THREAD

**Issue by JiahuiChen-GitHub** [baaivision/EVA#47]
Thank you for your great work! 

There seems to be a code error [here](https://github.com/baaivision/EVA/blob/master/EVA-02/det/detectron2/modeling/backbone/vit.py#L120), these permutation operations should not exist when `xattn = False`. They should be moved to [line 125](https://github.com/baaivision/EVA/blob/master/EVA-02/det/detectron2/modeling/backbone/vit.py#L125) in `if self.xattn:`.

Thanks.

**Comment by Yuxin-CV** [comment]
Hi @JiahuiChen-GitHub, thanks for pointing this out!
