### ISSUE TITLE
Typos VA/EVA-02/asuka/README.md

### ISSUE THREAD

**Issue by jzhang38** [baaivision/EVA#50]
You always give the pretraining scripts as "python -m torch.distributed.launch --nproc_per_node=8 --nnodes=${WORLD_SIZE} --node_rank=${RANK} --master_addr=${MASTER_ADDR} --master_port=12345 --use_env **run_beit_pretraining.py**" I believe you mean **run_eva_pretrianing.py**?

**Comment by Yuxin-CV** [comment]
Hi @jzhang38, thanks for pointing out this issue!

We have fixed this issue in https://github.com/baaivision/EVA/commit/fdf8835743b284013d053a65c0f8a669101d2f00.
