### ISSUE TITLE
How to handle pos encoding with different resolution?

### ISSUE THREAD

**Issue by YAOYI626** [baaivision/EVA#52]
Thank authors for the great great work!

In EVA-02, the model changes position encoding from `RPE` to `RoPE`. I'd like to understand how this change works when given different resolutions with pretrained one. Is it possible to input any resolution to do **zero-shot** tasks? Or it has to be finetuned when given different resolutions like detection or segmentation?

**Comment by YAOYI626** [comment]
Or is the "crop" process is described in any paper/material which I can refer to? Thanks in advance!

**Comment by Yuxin-CV** [comment]
Hi @YAOYI626, please refer to:

- https://arxiv.org/abs/2012.07177

- https://github.com/baaivision/EVA/blob/master/EVA-02/det/projects/ViTDet/configs/common/coco_loader_lsj.py

- https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md#new-baselines-using-large-scale-jitter-and-longer-training-schedule

- https://github.com/baaivision/EVA/blob/0228acdec313480cd010e0e316cd87dc374e534a/EVA-02/seg/configs/eva02/upernet/upernet_eva02_base_12_512_slide_60k.py#L17

**Comment by YAOYI626** [comment]
Thanks @Yuxin-CV! for your in-time and precise reply, which solves all my questions. I'd like to close this issue.
