### ISSUE TITLE
EVA-CLIP + ImageNet finetuning

### ISSUE THREAD

**Issue by SimJeg** [baaivision/EVA#55]
Hello, 

Did you perform an experiment where you finetune an EVA-CLIP model on ImageNet ? I wonder if you would get similar or superior performance compared to finetuning the MIM model. How do you think it would compare ? My motivation for this question is the ability to get the best of both performance and generalization through methods such as [wise-ft](https://github.com/mlfoundations/wise-ft).

Thanks,
Simon

**Comment by Quan-Sun** [comment]
Hello @SimJeg . We have not directly fine-tuned EVA-CLIP on ImageNet, but we have released all the weights necessary for such experiments. We welcome researchers to explore fine-tuning EVA-CLIP on ImageNet and other downstream tasks, and we are excited to see how it performs in these settings.
