### ISSUE TITLE
Use of both absolute and rotary positional embedding?

### ISSUE THREAD

**Issue by jzhang38** [baaivision/EVA#58]
https://github.com/baaivision/EVA/blob/11983c3715bd48bccd6f749e2f95cc2521729bac/EVA-02/asuka/modeling_pretrain.py#L38
It seems that EVA-02 uses both absolute and rotary positional embedding. Is my understanding correct here?

**Comment by Yuxin-CV** [comment]
Yes, we uses both the abs pos and rope.
