### ISSUE TITLE
missing keys in source state_dict: blocks.x.attn.qkv.bias

### ISSUE THREAD

**Issue by duanduanduanyuchen** [baaivision/EVA#59]
I'm trying to use the pretrained weights in eva1:
[eva_psz14to16](https://huggingface.co/BAAI/EVA/resolve/main/eva_psz14to16.pt)
When I init a ViT using timm and load weights, I find missing and unexpected keys. There are 'q_bias' and 'v_bias' in the weights of each block but no 'k_bias', while the expected key is actually 'qkv.bias'. Is this a trick or an error in saving weights? How can I load the pretrained weights when there is only one key(qkv_bias) in timm vision transformer model but no k_bias in the existing weights?
(I also find this fact in [eva_21k_1k_560px_psz14_ema](https://huggingface.co/BAAI/EVA/resolve/main/eva_21k_1k_560px_psz14_ema_89p7.pt) and maybe also in other weights files)

**Comment by Yuxin-CV** [comment]
Hi @duanduanduanyuchen, we don't use `k_bias` following the original BEiT setting (`qkv_bias=False`): https://github.com/microsoft/unilm/blob/e78edaa01ccc1e510d13e49df5b15cb150326fb7/beit/modeling_finetune.py#L252.

If you use `timm`, EVA-01 has already been added to `timm` (do not init. EVA with `vit.py`, use `beit.py`): 
- https://github.com/huggingface/pytorch-image-models#dec-6-2022
- https://github.com/huggingface/pytorch-image-models/blob/1885bdc4318cc3be459981ea1a26cd862220864d/timm/models/beit.py#L424

For the reason, please refer to: https://www.zhihu.com/question/506218961

**Comment by duanduanduanyuchen** [comment]
Thank you for your quick reply! I will try beit this time.
