### ISSUE TITLE
Questions about downstream transfer learning & fine-tuning performance.

### ISSUE THREAD

**Issue by MengzhangLI** [baaivision/EVA#60]
Hi, @Quan-Sun , @Yuxin-CV and other authors of EVA.

Firstly, thanks for your excellent work and congrats for acceptance & highlight of CVPR'2023. 

I am wondering how to use EVA as upstream foundation model to other tasks, such as remote sensing or medical image area. Currently my main idea is beyond "continue training" which means directly use your provided weights to train some specific tasks, I want to follow some methods proved in NLP and computer vision (like Adapter or Visual Prompt Tuing). 

I would try to use Adapter mechanism like ViT-Adapter in EVA, do you think it can work? Because ViT-Adapter works in ViT and its performance in Swin Transformer is not as good as ViT (although I don't know why yet).

Also, I am new to foundation model area and my interest is on using foundation model (like EVA) for downstream fine-tuning tasks, do you have some recommended paper or github repositories? 

Thanks in advance!

Mengzhang LI

**Comment by Yuxin-CV** [comment]
Hello @MengzhangLI,
Thank you for your enthusiasm in our work.
We posit the optimal approach to transferring EVA or any other extensive representations is to end-to-end fine-tune all weights with a meticulous hyperparameter search. However, if resources are limited, we recommend the following two methods to adapt pre-trained EVA for downstream tasks:
1. Select the largest CLIP vision encoder (e.g. EVA-02-CLIP-E+), freeze all pretrained weights, and add & ft lightweight randomly initialized parameters (i.e. adapters).
2. Choose a moderately sized MIM pre-trained EVA (e.g. EVA-02-L), and end-to-end fine-tune all pretrained weights for your task of interest (with a meticulous hyperparameter search).

**Comment by Quan-Sun** [comment]
Hi @MengzhangLI. If you were interested in PEFT, I would like to recommend [Towards a Unified View of Parameter-Efficient Transfer Learning](https://arxiv.org/abs/2110.04366).
