### ISSUE TITLE
What is the input distribution of eva-2?

### ISSUE THREAD

**Issue by 1049451037** [baaivision/EVA#66]
How should I preprocess my image input? Should I normalize it to [-1, 1]? or normalize it to [0, 1]? Is there any docs available?

**Comment by Yuxin-CV** [comment]
Please refer to: 
- https://github.com/baaivision/EVA/blob/802e195104e67989777d4f696833368463046386/EVA-02/asuka/datasets.py#L34

- https://huggingface.co/timm/eva02_large_patch14_448.mim_m38m_ft_in1k

**Comment by 1049451037** [comment]
Got it. Thank you.
