### ISSUE TITLE
Implementation details of EVA-CLIP

### ISSUE THREAD

**Issue by TempleX98** [baaivision/EVA#69]
Thanks for your great work! In the EVA-CLIP paper, you adopt FLIP to improve efficiency, but I can't find the implementation of FLIP in the current codebase.

**Comment by Quan-Sun** [comment]
Hi @TempleX98, Thanks for your interests in our work. You can find the implementation [here](https://github.com/baaivision/EVA/blob/master/EVA-CLIP/rei/eva_clip/transformer.py#L97).

**Comment by TempleX98** [comment]
thanks!
