### ISSUE TITLE
How to get EVA02_CLIP_L_psz14_224to336 by myself?

### ISSUE THREAD

**Issue by yijicheng** [baaivision/EVA#73]
Thanks for your excellent work!

How can I set the parameter to get `EVA02_CLIP_L_psz14_224to336` with your code base?

**Comment by Quan-Sun** [comment]
@yijicheng check [here](https://github.com/baaivision/EVA/blob/master/EVA-CLIP/rei/training/interpolate_patch14_224to336.py)

**Comment by yijicheng** [comment]
Thank you so mush!
