### ISSUE TITLE
Lazy deepspeed and apex imports

### ISSUE THREAD

**Issue by aluo-x** [baaivision/EVA#87]
Currently EVA-CLIP will attempt to import deepspeed and apex even if they are not present on the host system. 
I propose that deepspeed and apex are wrapped inside an try/except block, and the code is modified to not use Apex layernorm if apex cannot be imported.

**Comment by Quan-Sun** [comment]
Thanks for your suggestion. We have already updated the code.

**Comment by Quan-Sun** [comment]
> Do we have to use the FusedLayerNorm when using the weight of EVA-2-L?

@vateye  No, FusedLayerNorm is not required. you can nn.LayerNorm

**Comment by aluo-x** [comment]
Thanks! I will close the issue for now.

**Comment by aluo-x** [comment]
Thanks! I will close the issue for now.
