### ISSUE TITLE
Plans for training high resolution pretraining only models?

### ISSUE THREAD

**Issue by Parskatt** [baaivision/EVA#89]
Hi, great work!

I'm working with geometric correspondence, where finetuning on imagenet typically degrades performance.
However, I only found pretrained models on 224x224 resolution in this repo, which is too low.
I don't have the resources to fine-tune the pretraining stage myself, need to rely on mostly frozen weights. 

I'm wondering whether you've considered providing a higher resolution pretraining only model?
For example DINOv2 uses high resolution pretraining, which I've found gives huge performance gains for geometric tasks.

Note: I'd like to use EVAv2 instead of DINOv2 due to the much more permissive license

**Comment by Quan-Sun** [comment]
Hi Parskatt, 

Thanks for your interest in our work. We have a pretrained large-size EVA-CLIP model with 336x336 resolution([EVA02_CLIP_L_336_psz14_s6B](https://huggingface.co/QuanSun/EVA-CLIP/blob/main/EVA02_CLIP_L_336_psz14_s6B.pt)) and you can try its visual encoder.

**Comment by Parskatt** [comment]
Thanks!
